spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
        defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: always
      continue-on-error: on
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DEFAULT_ADMIN_PASS}
    username: ${DEFAULT_ADMIN_USERNAME}
    url: jdbc:mysql://localhost:3306/dictionary?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

binding-result-package: org.springframework.validation.BindingResult
